### ISSUE TITLE
BV Calculations with heat inefficient iATMs and Streak LRMs are inaccurate

### ISSUE THREAD

**Issue by brstrommen** [WEKarnesky/solarisskunkwerks#13] opened 2019-07-10 22:51 UTC
**Describe the bug**
The BV calculation for some units is not accurate.  One such unit is the Mad Cat Z, but there are likely others.

**To Reproduce**
Open Mad Cat (Timber Wolf) Z
View BV (3003)

**Expected behavior**
BV should instead equal 2923
http://masterunitlist.info/Unit/Details/5822/mad-cat-timber-wolf-z

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Windows 10

**Comment by brstrommen** [comment] 2019-07-11 00:24
When calculating BV for heat inefficient mechs, SSW only checks whether a weapon is a streak weapon and not whether it's a streak SRM (per Tech Manual page 303, under Step 2: Calculate Offensive Battle Rating, "reduce by half the heat points generated by Streak SRMs").  Any mech that is heat inefficient and uses Streak LRMs and iATMs will likely be affected by the same issue.  Forcing GetBVHeat to ignore the streak check for the Timber Wolf Z results in the correct 2923 BV calculation.

**Comment by brstrommen** [comment] 2019-07-11 00:56
Other affected mechs may include:
Cougar X
Cougar X2
Cougar X3
Hoplite HOP-4X

(But for possibly unrelated reasons)

**Comment by Algebro7** [comment] 2019-07-11 03:37
Thanks for the report. Do you have a list of weapon types that should be reduced by 50% compared to those that should not? Is it just SRMs that should get teh 50% reduction? I don't have a copy of the tech manual so I'm not sure how to look it up.

Also, is "heat inefficient" a specific attribute of mechs that needs to be checked for? I tried searching in the code but I didn't see any references to it.

**Comment by Algebro7** [comment] 2019-07-11 13:45
I think the issue for streak BV's is fixed by [this commit](https://github.com/Algebro7/sswlib/commit/f3819fe9a145bc81d6dd8621c4248aaec2b6d2a9), at least it fixes the Timberwolf Z and the Hoplite. The Cougar X's are still wrong but I'm not sure why. Could it be related to defensive BV modifiers for the LRM ammo in the side torso?

**Comment by Algebro7** [comment] 2019-07-11 19:48
Is it safe to assume this particular issue related to streak weapons is fixed? If so, I will merge and we can work on the cougars separately in #14

**Comment by brstrommen** [comment] 2019-07-11 22:08
Yes, this issue should now be resolved.

**Comment by WEKarnesky** [comment] 2019-07-11 22:26
I'm going to mark this as closed then, and mark it as done on #14's meta list.  If further testing shows the issue is not fully resolved please let us know.

**Closed as completed by WEKarnesky** 2019-07-11 22:26 UTC
Labels: bug, help wanted, good first issue

**Comment by WEKarnesky** [comment] 2019-07-12 19:03
As a quick note, the three Cougars mentioned above have all been confirmed to be calculating correctly.  the issue was the Master Unit List was using the incorrect value and not accounting for the built-in C.A.S.E.
